# Default values for AppsCodeServer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  registry: masudjuly02
  repository: appscodeserver
  tag: latest
  pullPolicy: IfNotPresent
  port: 8080

labels:
  api: latest

service:
  type: NodePort
  port: 8080
  targetPort: 8080

ingress:
  host: software.farm
  path: /
  port: 8080
